# Generated by Django 4.1.6 on 2023-03-15 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('barra', models.IntegerField()),
                ('vto', models.DateField()),
                ('codigo', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('tipo_impuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='precio_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipo', models.CharField(max_length=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='movimiento_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateField()),
                ('tipo', models.CharField(max_length=10)),
                ('proveedor', models.CharField(max_length=100)),
                ('numero_referencia', models.CharField(max_length=20)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='entrada_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=11)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=11)),
                ('numero_factura', models.CharField(max_length=20)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_producto.producto')),
            ],
        ),
    ]
