# Generated by Django 4.1.6 on 2023-03-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='vendedores',
        ),
    ]
