# Generated by Django 4.1.6 on 2023-04-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendedores', '0003_rename_vendedores_vendedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendedor',
        ),
    ]
