# Generated by Django 4.1.6 on 2023-03-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('vto', models.DateField()),
                ('cod_verificador', models.CharField(max_length=4)),
                ('operador', models.CharField(max_length=50)),
                ('precargado', models.CharField(max_length=2)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente')),
            ],
        ),
    ]
