# Generated by Django 4.1.6 on 2023-04-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturacion', '0005_cliente_producto_vendedor_tarjeta_precio_producto_and_more'),
        ('app_clientes', '0002_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='id_cliente',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='tarjeta',
        ),
    ]
