# Generated by Django 4.1.6 on 2023-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facturacion', '0002_remove_factura_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='importe_impuesto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='importe_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
