# Generated by Django 4.1.6 on 2023-03-15 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0002_tarjeta'),
        ('app_facturacion', '0003_alter_factura_importe_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente'),
        ),
    ]
